from . import res_config_settings
from . import ir_attachment
from . import tender_job
from . import tender
from . import bidder
from . import payment
from . import work_experience
from . import eligibility_criteria
from . import tender_dashboard
from . import bidder_check
from . import extraction_master
from . import custom_extraction
from . import client_query
from . import mail_bot_inherit
from . import quick_doc_chat
from . import discuss_channel
from . import property_ai_query
